<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJymjfiS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJymjfiS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJymjfiS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJymjfiS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJymjfiS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JymjfiS',
    'container.build_id' => '48a2a866',
    'container.build_time' => 1622151178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJymjfiS');
